e-gov/TARA-Server

- doc/Configuration.md
- src/main/webapp/WEB-INF/classes/log4j2.xml
AUT-1113 - removed redundant loggers, added samples of syslog appenders for (cas.log, audit.log and stats.log)
> AUT-113 - removed redundant loggers, added samples of syslog appenders for (cas.log, audit.log and stats.log)

- pom.xml
- src/main/java/ee/ria/sso/config/TaraLoggingConfiguration.java
- src/main/java/ee/ria/sso/logging/IncidentLoggingMDCServletFilter.java
Add hazelcast dependencies. Update logging filter order.
> AUT-141 - ticket and webflow clustering support

- src/main/java/ee/ria/sso/validators/OidcAuthorizeRequestValidationServletFilter.java
- src/test/java/ee/ria/sso/validators/OidcAuthorizeRequestValidationServletFilterTest.java
AUT-192 - append parameters correctly when redirect_uri already contains query part
> AUT-192 - append parameters correctly when redirect_uri already contains query part

- doc/Configuration.md
- pom.xml
- src/main/java/ee/ria/sso/config/TaraConfiguration.java
- src/main/java/ee/ria/sso/config/TaraProperties.java
- src/main/java/ee/ria/sso/flow/ThymeleafSupport.java
- src/main/java/ee/ria/sso/flow/action/TaraTicketGrantingTicketCheckAction.java
- src/main/java/ee/ria/sso/utils/HashingUtil.java
- src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
- src/main/java/org/apereo/cas/oidc/web/OidcSecurityInterceptor.java
- src/main/resources/dynamic.properties
- src/main/webapp/WEB-INF/classes/templates/casBankRedirectView.html
- src/main/webapp/WEB-INF/classes/templates/casMIDLoginCode.html
- src/main/webapp/WEB-INF/classes/templates/casSmartIdVerificationCode.html
- src/main/webapp/WEB-INF/classes/templates/error.html
- src/main/webapp/WEB-INF/classes/templates/error/401.html
- src/main/webapp/WEB-INF/classes/templates/error/403.html
- src/main/webapp/WEB-INF/classes/templates/error/404.html
- src/main/webapp/WEB-INF/classes/templates/error/423.html
- src/main/webapp/WEB-INF/classes/templates/fragments/loginform.html
- src/main/webapp/WEB-INF/classes/templates/fragments/logintabs.html
- src/main/webapp/WEB-INF/classes/templates/fragments/taraheader.html
- src/main/webapp/WEB-INF/classes/webflow/login/login-webflow.xml
- src/test/java/ee/ria/sso/config/TestTaraConfiguration.java
- src/test/java/ee/ria/sso/config/ThymeleafSupportTest.java
- src/test/java/ee/ria/sso/flow/action/TaraTicketGrantingTicketCheckActionTest.java
- src/test/java/org/apereo/cas/oidc/web/OidcSecurityInterceptorTest.java
- src/test/resources/application-test.properties
* introduce new parameter to enable/disable the forced re-authentication at /oidc/authorize endpoint
* refacto - remove dead code + move all thymeleaf support methods from TaraProperties to separate class
* exclude the default user-details.properties from war overlay
* update docs
> AUT-4 - force auth renewal with oid/authorize

- doc/Configuration.md
- pom.xml
- src/main/java/ee/ria/sso/authentication/TaraAuthenticationHandler.java
- src/main/java/ee/ria/sso/authentication/principal/TaraPrincipal.java
- src/main/java/ee/ria/sso/authentication/principal/TaraPrincipalFactory.java
- src/main/java/ee/ria/sso/config/TaraOidcConfiguration.java
- src/main/java/ee/ria/sso/flow/AbstractFlowExecutionException.java
- src/main/java/ee/ria/sso/oidc/TaraOidcIdTokenGeneratorService.java
- src/main/java/ee/ria/sso/oidc/TaraOidcUserProfileDataCreator.java
- src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
- src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointController.java
- src/test/java/ee/ria/sso/authentication/TaraAuthenticationHandlerTest.java
- src/test/java/ee/ria/sso/authentication/principal/TaraPrincipalFactoryTest.java
- src/test/java/ee/ria/sso/config/TestTaraConfiguration.java
- src/test/java/ee/ria/sso/oidc/MockPrincipalUtils.java
- src/test/java/ee/ria/sso/oidc/TaraOidcIdTokenGeneratorServiceTest.java
- src/test/java/ee/ria/sso/oidc/TaraOidcUserProfileDataCreatorTest.java
- src/test/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointControllerTest.java
Changes
* expose tara principal claims in userinfo endpoint
* userinfo endpoint is enabled by default
> AUT-260 - expose tara principal claims in userinfo endpoint

- src/main/java/ee/ria/sso/service/AbstractService.java
- src/main/java/ee/ria/sso/service/banklink/BanklinkAuthenticationService.java
- src/main/java/ee/ria/sso/service/eidas/EidasAuthenticationFailedException.java
- src/main/java/ee/ria/sso/service/eidas/EidasAuthenticationService.java
- src/main/java/ee/ria/sso/service/eidas/EidasAuthenticator.java
- src/main/java/ee/ria/sso/service/manager/ManagerServiceImpl.java
- src/main/java/ee/ria/sso/statistics/StatisticsRecord.java
- src/main/webapp/WEB-INF/classes/messages.properties
- src/main/webapp/WEB-INF/classes/messages_et.properties
- src/main/webapp/WEB-INF/classes/messages_ru.properties
- src/test/java/ee/ria/sso/service/eidas/EidasAuthenticationServiceTest.java
- src/test/java/ee/ria/sso/service/manager/ManagerServiceImplTest.java
- src/test/java/ee/ria/sso/statistics/StatisticsHandlerTest.java
- src/test/java/ee/ria/sso/statistics/StatisticsRecordMatcher.java
- src/test/java/ee/ria/sso/statistics/StatisticsRecordTest.java
- src/test/java/ee/ria/sso/statistics/TaraStatHandlerTest.java
* add country to statistics log
* add input sanity checking and new translation for an error it produces
* fix person identifier parsing (eidas-client response)
> AUT-288, AUT-293 - statistics log update

- doc/Configuration.md
- src/main/java/ee/ria/sso/Constants.java
- src/main/java/ee/ria/sso/config/TaraOidcConfiguration.java
- src/main/java/ee/ria/sso/config/eidas/EidasConfigurationProvider.java
- src/main/java/ee/ria/sso/flow/action/InitializeLoginAction.java
- src/main/java/ee/ria/sso/oidc/OidcAuthorizeRequestValidationServletFilter.java
- src/main/java/ee/ria/sso/oidc/TaraScopeValuedAttribute.java
- src/main/java/ee/ria/sso/oidc/TaraScopeValuedAttributeName.java
- src/main/webapp/WEB-INF/classes/webflow/login/login-webflow.xml
- src/test/java/ee/ria/sso/flow/action/InitializeLoginActionTest.java
- src/test/java/ee/ria/sso/oidc/OidcAuthorizeRequestValidationServletFilterTest.java
…ibute is present in request scope
> AUT-380 - Skip UI for eIDAS only authentication if eidas country attribute is present in scope

- pom.xml
- src/main/java/ee/ria/sso/service/smartid/SmartIDAuthenticationService.java
- src/main/java/ee/ria/sso/service/smartid/SmartIDAuthenticationValidatorWrapper.java
- src/main/java/ee/ria/sso/service/smartid/SmartIDClient.java
- src/test/java/ee/ria/sso/service/smartid/SmartIDAuthenticationServiceTest.java
- src/test/java/ee/ria/sso/service/smartid/SmartIDAuthenticationValidatorWrapperTest.java
- src/test/java/ee/ria/sso/service/smartid/SmartIDClientTest.java
- src/test/java/ee/ria/sso/service/smartid/SmartIDMockData.java
AUT-425 - update CAS from 5.3.9 to 5.3.14 + update dependencies
> AUT-425 - update CAS from 5.3.9 to 5.3.14 + update dependencies

- src/main/java/ee/ria/sso/authentication/TaraAuthenticationHandler.java
- src/main/java/ee/ria/sso/authentication/principal/TaraPrincipal.java
- src/main/java/ee/ria/sso/oidc/TaraOidcIdTokenGeneratorService.java
- src/main/java/ee/ria/sso/oidc/TaraScope.java
- src/main/java/ee/ria/sso/service/mobileid/MobileIDAuthenticationService.java
- src/main/java/ee/ria/sso/service/mobileid/MobileIDCredential.java
- src/test/java/ee/ria/sso/authentication/TaraAuthenticationHandlerTest.java
- src/test/java/ee/ria/sso/authentication/principal/TaraPrincipalFactoryTest.java
- src/test/java/ee/ria/sso/oidc/MockPrincipalUtils.java
- src/test/java/ee/ria/sso/oidc/TaraOidcIdTokenGeneratorServiceTest.java
- src/test/java/ee/ria/sso/oidc/TaraOidcUserProfileDataCreatorTest.java
> Phone number in Mobile-ID personal data

- src/main/java/ee/ria/sso/service/idcard/OCSPValidator.java
- src/test/java/ee/ria/sso/service/idcard/OCSPValidatorTest.java
> AUT-496 - OCSP failover new terms

- src/main/webapp/WEB-INF/classes/messages.properties
- src/main/webapp/WEB-INF/classes/messages_et.properties
- src/main/webapp/WEB-INF/classes/messages_ru.properties
- src/test/resources/messages.properties
- src/test/resources/messages_et.properties
- src/test/resources/messages_ru.properties
> AUT-504 - id.ee linkide uuendus

- src/main/java/ee/ria/sso/service/mobileid/MobileIDAuthenticationService.java
- src/test/java/ee/ria/sso/service/banklink/BanklinkAuthenticationServiceTest.java
- src/test/java/ee/ria/sso/service/mobileid/MobileIDAuthenticationServiceTest.java
> AUT-416 - Mobile-ID display message based on TARA language

- src/main/java/ee/ria/sso/service/idcard/IDCardAuthenticationService.java
- src/main/java/ee/ria/sso/service/idcard/IDCardController.java
- src/test/java/ee/ria/sso/service/idcard/IDCardAuthenticationServiceTest.java
- src/test/java/ee/ria/sso/service/idcard/IDCardControllerTest.java
> AUT-217 - Log START_AUTH at idcard endpoint

- src/main/java/ee/ria/sso/service/idcard/OCSPValidator.java
> AUT-506 - Log OCSP detailed error

- src/main/java/ee/ria/sso/service/eidas/EidasAuthenticator.java
- src/main/webapp/WEB-INF/classes/log4j2.xml
- src/test/resources/log4j2-test.xml
- src/test/resources/log4j2.xml
> AUT-76 - Log external system requests

- src/main/java/ee/ria/sso/statistics/StatisticsRecord.java
> AUT-133 - More detailed statistics error log

- src/main/java/ee/ria/sso/logging/ApplicationPropertiesLogger.java
> AUT-77 - Log application properties on startup

- src/main/java/ee/ria/sso/flow/ThymeleafSupport.java
- src/test/java/ee/ria/sso/config/ThymeleafSupportTest.java
> AUT-549 - Fixed CAS auth method checking

- doc/Configuration.md
- src/main/java/ee/ria/sso/config/TaraProperties.java
- src/main/java/org/apereo/cas/security/ResponseHeadersEnforcementFilter.java
- src/test/java/org/apereo/cas/security/ResponseHeadersEnforcementFilterTest.java
- src/test/resources/application-test.properties
- src/test/resources/static/assets/test-file.txt
> AUT-546 - Cache for static resources

- pom.xml
> AUT-551 - Dependency updates

- src/main/webapp/WEB-INF/classes/messages.properties
- src/main/webapp/WEB-INF/classes/messages_et.properties
- src/main/webapp/WEB-INF/classes/messages_ru.properties
- src/main/webapp/WEB-INF/classes/templates/fragments/logintabs.html
> AUT-557 - Updated translations
